-- Таблица планов
CREATE TABLE FLOORPLAN (
    ID_FLOORPLAN INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    IMAGE VARCHAR(255) NOT NULL,
    WIDTH INTEGER DEFAULT 800,
    HEIGHT INTEGER DEFAULT 600,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Добавляем первичный ключ
ALTER TABLE FLOORPLAN ADD CONSTRAINT PK_FLOORPLAN PRIMARY KEY (ID_FLOORPLAN);

-- Таблица точек на плане
CREATE TABLE FLOORPLAN_POINT (
    ID_POINT INTEGER NOT NULL,
    ID_FLOORPLAN INTEGER NOT NULL,
    X_POS FLOAT DEFAULT 0,
    Y_POS FLOAT DEFAULT 0,
    ID_DEV INTEGER,
    POINT_TYPE VARCHAR(20) DEFAULT 'door',
    LABEL VARCHAR(100)
);

-- Добавляем первичный ключ
ALTER TABLE FLOORPLAN_POINT ADD CONSTRAINT PK_FLOORPLAN_POINT PRIMARY KEY (ID_POINT);

-- Генераторы для Firebird
CREATE GENERATOR GEN_FLOORPLAN_ID;
CREATE GENERATOR GEN_FLOORPLAN_POINT_ID;

-- Триггеры для автоинкремента
SET TERM ^ ;
CREATE TRIGGER TRG_FLOORPLAN_BI FOR FLOORPLAN
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID_FLOORPLAN IS NULL) THEN
        NEW.ID_FLOORPLAN = GEN_ID(GEN_FLOORPLAN_ID, 1);
END^

CREATE TRIGGER TRG_FLOORPLAN_POINT_BI FOR FLOORPLAN_POINT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID_POINT IS NULL) THEN
        NEW.ID_POINT = GEN_ID(GEN_FLOORPLAN_POINT_ID, 1);
END^
SET TERM ; ^

-- Внешний ключ (теперь должен работать, так как есть первичные ключи)
ALTER TABLE FLOORPLAN_POINT ADD CONSTRAINT FK_FLOORPLAN_POINT
    FOREIGN KEY (ID_FLOORPLAN) REFERENCES FLOORPLAN(ID_FLOORPLAN) ON DELETE CASCADE;

